---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
