---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.18.1
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # valuesFrom:
  #   - kind: Secret
  #     name: grafana-login
  #     valuesKey: values.yaml
  values:
    alertmanger:
      enabled: true
      route:
        main:
          enabled: true
          hostnames: ["alertmanager.endsys.cloud"]
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https
    grafana:
      enabled: true
      defaultDashboardsTimezone: browsers
      route:
        main:
          enabled: true
          hostnames: ["grafana.endsys.cloud"]
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https
    prometheus:
      route:
        main:
          enabled: true
          hostnames: ["prometheus.endsys.cloud"]
          parentRefs:
            - name: internal
              namespace: kube-system
              sectionName: https