---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: seaweedfs
      namespace: seaweedfs
  values:
    # Use Kopia (replaces Restic) for file-system backup
    deployRestic: true
    # We are not using cloud provider snapshots
    snapshotsEnabled: false
    # Reference the 'cloud' key from the secret in step 02
    credentials:
      secretName: velero-s3-credentials
      secretKey: cloud
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero # The bucket name SeaweedFS will use
        config:
          region: default
          s3ForcePathStyle: "true"
          s3Url: http://seaweedfs-s3.seaweedfs.svc:8333