apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio
type: Opaque
stringData:
  accesskey: ENC[AES256_GCM,data:mtud04U=,iv:WsTKuZgEopHy7HyNQQQuyxaAunwNhqjQiNxWR58Fc1Q=,tag:rIBhSpO2iuX2fUdkTVwM+w==,type:str]
  secretkey: ENC[AES256_GCM,data:rEWXntZcSSA=,iv:mH6Zgk+yuYyrA0R6WwNS59yhkykeGwb2hOiddTtnknE=,tag:3CTvING0K3GLuMDDpvCHww==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNclpWOFZHZE94SUxUS1pi
        S3pQM1Q3YXVWR2J3SUVVdzlPb1FSczc5WUNFCjUrT0tUcFJqUU9NcEVVaEd3S0pk
        ZzhNd0JiQ0wvQ2xtVmxiNVdrZE5FODQKLS0tIEZ0Zm9Uc2VFcHpNTXFNekI3T0pL
        NHFOVEFLV21Yd0RaZWFHRWNZQWZtbkUKEdJT7RcNlFQB1IaSkKMhm78A7Zkh6r1s
        w3xVeMZyqPaXNIm28u/j+M+mEuzE13u08DAXCd1GaW3fF1xkYQ0CtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-08T18:06:57Z"
  mac: ENC[AES256_GCM,data:hFfkULSJKj2hRdSXhpo8yJf5fesoTMTNU4BAxfvOIk5m6UewGgs42u9bKEpzD19+mCzsHWWzjrn9wje81ODlF4QAfPEyhhoFTQIiDLfQJR40wY4Rejs4MVW4AtbxLop+HofKZq9YnVEBmOqHymy+iwldm4npCZj7g5NJZKcYyBc=,iv:YOEC/KX8a3mwTfH5DOhC4p16SAQ7QpPIjG+bZIWDsiA=,tag:QhwHndwljWjXXgSn9STbSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
