# ---
# apiVersion: minio.min.io/v2
# kind: Bucket
# metadata:
#   name: velero
#   namespace: minio
# spec:
#   name: velero
#   tenant: minio
---
# clusters/my-cluster/velero/minio-bucket-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-velero-bucket
  namespace: minio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc-container
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for MinIO service to be ready..."
          until mc alias set minio http://minio.velero.svc.cluster.local:9000 $(MINIO_ROOT_USER) $(MINIO_ROOT_PASSWORD); do
            echo "MinIO not ready yet, retrying in 5s..."
            sleep 5
          done
          echo "MinIO is ready. Checking for 'velero' bucket..."
          if ! mc ls minio/velero; then
            echo "Bucket 'velero' does not exist. Creating it..."
            mc mb minio/velero
          else
            echo "Bucket 'velero' already exists."
          fi
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-password
              key: rootUser
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-password
              key: rootPassword