# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qVVab+OAXaoIT1LjGIHN5xC0c0ZegaJHhw4ZsvKMZhY=,iv:pzPj0KTWtNUj4qzZeuMCWx1CPraWUm2HDLGsU4Gr4yo=,tag:H7VUooIDMGRIK7eGrguQQQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t348q6m2g5e0g83ud86399cre7qtt2ykm2gt5vrmy68remzu9slqfd2js5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNW15N28zUkNLVlhvR0k4
        QmhSazVvc2RwZEFabmhwWlF1T1ZzamhpMUdnCmd3VUFubGNLVHBzOGhtcHlyenVD
        MWwyMk9kQlR5R3V3MHlvSVVrVkxYMTgKLS0tIDBNQTYvSVVjc2p4RFlXUGsrRjB6
        clJyQXVxRjNCMUNXanFEbGFBYVRKU2sKmH+JnLRSXhFdec0MjE86AdjscT6mYS8W
        Ey+ieA16rcxKny4PFulokvdtSlc2SK4zxJRq496UvpiucORaAG3+rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T21:14:45Z"
  mac: ENC[AES256_GCM,data:PBgofZUxniXPb8LNwMMb2BNlJCPRU6lSDhSvG/ScCyPiFKyqZIWe8Ex98BOnqe8Y1sumJBEkr9DijSmIcIt5O+n83fhghXX1R72OPoygrEjWmxA88fg4ZqiARAs0HvoYNDMEW2M6siz5VJxNl9Xt1+i+Y/kz7bOW9mgpbmm7xNQ=,iv:5RvAH52MpRkDOo9JU9OjMdY31dk+MwpFDf9tVLlOnKs=,tag:tA9AMDFS/zroCIXA3KZuDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
