---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
spec:
  parentRefs:
  - name: internal         # your existing Gateway
    namespace: kube-system
    sectionName: https             # if it lives elsewhere
  hostnames: ["n8n.endsys.cloud"]
  rules:
    - backendRefs:
        - identifier: app
          port: 80