---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./cnpg-backup-netbird-postgres.yaml
  - ./postgres-cluster.yaml
  - ./helmrelease.yaml
  - ./routes.yaml
