# https://artifacthub.io/packages/helm/open-webui/open-webui?modal=values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocm-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: gpu-operator-charts
      version: v1.2.0
      sourceRef:
        kind: HelmRepository
        name: rocm-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3