apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jHxfC1aBH/4Naw8WIHab8MhAZZBAZr9e+qgikAvIWahOdOvr,iv:U59qbRlDvOkuczbYqQuyFTpJOXTbMCAkMP0GfBGAFm4=,tag:tKQm7r3jqTMt1NDuVCcmQw==,type:str]
    credentials.json: ENC[AES256_GCM,data:3GzrKAzaCfgnYaPpUsUZE1AX7ekew0mcPg/dAFsJ1WaN1qYRrGMxvc/US5LXDRBaz4IUDWaJAuevK6q8zhJckd5275EfUKt5lSFvZTN0p3JXfy53CQ7xhU8vT6UnP7SeWyAkQQ1QLesKqr4nRn3eklpR20Syc07vm2C3okssiZ2ZimyiBYbSgM3wcK0RdN4Ckwm6F5/4IFqkYFhQ1pDI0Lk362tsyN5Rr2nDBk2W2A==,iv:2xxedbR1dUu81y+wOo9+yhE2HTi4AQCivEIPG/bbB5Y=,tag:S6EdfTqaHXO281Tqk40q1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnVYSm5IS2ovVDVxeERE
            d3Z6cEdGLzZ6S25nWVRnU1ROeU83YTJUMWdBCkFIZ2RMRGNFckRteFA0V3J2LzNi
            SDNTRzQ1Vms3Z0NRY3IveW9OcUk1NWMKLS0tIHpPNWJpbjZhc3Z4L09tVlpqSUZV
            dGVkbnZJWHBTRWVVVWdnTnpZc0kwcUkK72Kco9k+2T3mPgMx5nXQ9l6q4ygWQYjC
            2n4Mlj4xaLjZnuNMUdn2keXeE/YMsaZ2o7NMkP+DbASmAU2AXn/4bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T11:37:50Z"
    mac: ENC[AES256_GCM,data:6ys5x8Gi+pwXn7RUwgCQ5S0nlKR4Ba0aqrARWIUCBgfImE99pIIL9GTZqwSUcRPIUHIirJJfiztLhhQ4vdbXkhooJiOPs4I9+sz3GmSlL4nbZJjoEG41oUwptN84fraTIKMHieuelJlW1UjSlCKfillkAs3Rx2kNixYSvbU/Gfk=,iv:y39X5s7Gpchtqs98/vDci5sG533+kEmpq6JM9psTDHY=,tag:ckg22eGU0fPcLY178s86Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
