# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:TnwmBQagDlT3X2psa9eaRxsXG5pFyovdsvKMn735hebJwzwt,iv:9IRu7y5T14o8IEKreJvX8eLOoLHwXEBEBLzQjGHGDrY=,tag:nggGfXZxxhlPHWd+q1DGDQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:Jau1An+r0UiCku/I9edMTcc6T0zs7Rz+GkJSRrwZvx0+yJ2Qx4tJIaRes2H7agNt0PvNhzm5onfByraQT77L/2GV4dryOP7f23L6ozsVuoZmc8/L4w7BslBhQHMgINC+WyCxTZ9v5TTXTmY0c8DntVC49m+MHP3Cs/2CrXr6Htb0HWz36xBDOGmjGW1vL67COGBwYma36mTqWOjG809Ap8YdxVNThZVeQ1HYljBWjw==,iv:YXtN4B1fwBZxXNbvn49/3kCJQdhc5tw4+b3zVQG+KN4=,tag:II0LM5oXtG9HOUY8i/lJAQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t348q6m2g5e0g83ud86399cre7qtt2ykm2gt5vrmy68remzu9slqfd2js5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbExQSXpJRjVNVFpyMnVG
        ZGFPQTdVSW44TkFzU2hrZ1d4Sk9IWEhMNndjCmlYdlJzYmNXdWlvMTYwU2l6d0tm
        ckQ0ZWZYejJaVlBLeS9XNHFSVXV1dE0KLS0tIGxsUmwxRXZaK0JWblYyTWRMd2cr
        UWtiaHB6WkppcVpLeEhTbmxJV3d6Y3MKkcp2v1kJt8lYVmk23TadwmHTTDP987Wt
        jkCV6e2HMk87PmaZ9bl8YQ6ywX+n/EuIG6aLLLlLXs2hOxyZFEFNIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T21:14:45Z"
  mac: ENC[AES256_GCM,data:dIko5l72YV/8zLUI/2rbrLd9tUubP6R0b9bRRuFhVhGe0KDBcLtpeLB9pYAKPotuK7PuE/W2etNygiZZho5Zv+8JwCmxPXlxwxn8NnCCjRs6NQrBlg91FLVqmhPD5YoZLhjp7R3FHPOrXEyY9d9XpM35PhEzwHGVr9t7dPAiE38=,iv:UilpUqMskIPdMZsYjHh94G6hDdd5yAH3xfvq+kH/HQg=,tag:R/lWcEfOvWb2j10Ji2rNWA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
