apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HWxXOkw17bZjUCk8fnlTw9DVZqEvFEJ0CwlcOfpg9e9p2B6W,iv:1aSw+Qyg3BEtoyxCpPoar39XwpRkZeG6UnAMhTZj3J8=,tag:YuVulRbM8tqqZooHW6vABA==,type:str]
    credentials.json: ENC[AES256_GCM,data:RoacQegJ+O/I1eDgTJv9k/gRSw7am8sMC3zn/IOBPKNhJ7Z2uv68wtgtLQr6v9ueDr0LX0Ix+VfLOcptZaTLqPFEyENYr7mlnVd6xW6OZHPDj/DebxRD1gNS8Xzcvmojh3g4M1chUlGgEQSIAdoI80ur1aD4qW6m0l6mDEc6SbL1/maRRItwXzhUWMfbaIvWBmtZUqHJZEUKRvAY1HJOHWEvaZIyZXLH8EzFIBfe8g==,iv:bSSRJbTcLEUPxnfZRKrKIJIkdRw07nBHJUuWj6GtL7s=,tag:URMnEW00yNiTmRT2HHUL2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaEtEd1lIY29mY29LVFVy
            SHlvUW5wWUJpZXpjSmNGcEtRNlJ2UXRGNzIwCkRHb0kyeUlTQ1RiUkM2UU9iYXhW
            KzdlVTJqc3JodytEaThibmo1WWR6ZlUKLS0tIHpZVXpaMGI3TkNzUm9UM3EvV05Q
            S0EzZnJ5RmVPNHJqaGN5MXIweHVDTjQKLWDTxHmEx9/6m8gQg/rprh91xcUaA0gA
            kH7TkhQShK8VSWS9gLQlvXQSJfoxeUTYaZweoD/LvhOJrtPr3LE9iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:58:34Z"
    mac: ENC[AES256_GCM,data:hlVWISnG5qLSxNJUh23KPW7xemCsrA1B5aJHmEo7JuG988vRT4C3A2R4WcVmjcFZwbM0bS2qbt68x59U34XmHcLbQYvMKXE21PMDezLzATEP9YABAh32Pmny94E8bVKqrgDzHThqLtO+B95vv7oE42xrHR5REMmMxaHzxjYrhNk=,iv:10FH/U0uGi47B0IdjLNTZzcflkP+pEeT9TlFykHIBVk=,tag:2Ss79SSkaGIb+0HG2yV+KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
