# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:W64sgLrzWNZ8x6eWsldE/xPnFJw1O0QLMJIy89WDpG8e8Hiw6J8NXg==,iv:uZ1T6LJY3dA5qdnnyDcfbymhFfur5YKkHoSoYmQuduw=,tag:CTCiIXP49oB4XVlYhePB3g==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2trU1pnTGZIRGRxMm9M
        SUx1a3VZbFkwN3BZNzRQQS9LK1UwcGpRYVU4ClJrN0pMQXZEcjNpWVJsRDVkZ0tM
        d1JpWXRsTzc1VXdyY014L2NBczBqY3cKLS0tIHhIcDE3UE8rL1ErblZGNDZnTnBj
        SjZlajArSC9nMWc5UjE2ZlJNRGlpSVUKT9Q3dAe/n9bO22WIkgZr0+xy7YaCM9m9
        AdeeKt3Bsm4fgBif+h8+NMb8HUuXThJPbZPIH7h7Msj40L2DMi95UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-14T17:25:21Z"
  mac: ENC[AES256_GCM,data:3Dni6kK98AuvjW1vremmDsjmaFuNg4GkRmBi3qF2At62MzWJ/hFx2C+B77WTJR9D2SCa8otEPRNhOHPjXFqdDTSqnXkDsoly9y6KySYDChuP0lgXE8BC2oEc7u+O6u3oPTE3+n4P8UVc+Cc4gM3XKC1vVt11b3HjZDHRTlM+5iI=,iv:vDit48z3qzDb7F060bHwfJA5v6tVxP4vmD8z3t1lT/U=,tag:wvrRM+vV1q1hxxwh582dig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
