# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kCTsUQG1Ib2NE0Rm,iv:TivokcEhxtk0tgjh8vRkmT3rYiTBko7PBUIysRtzHYM=,tag:jq3x48MlRbF3LxnSrdR/7w==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sXrxqjPmdKrS6qQsQ8zri6bgXKSNxTVcQDlsSaTy,iv:Tu2PLQMcT5WESNe889/LOreGofs2KJXFuYFFQAjMOsM=,tag:WApRl5Jy/YeiGbp+AZQHng==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:SKTLo1f2W1pKhs0LycmISpAIpmTEoxACqBGxc0ZpfY3Y0BM2,iv:GhjoFH0gyTP0F8XdOWRXe1monwO47Av9AScJG1IW0Bs=,tag:67hCn8q6lPT8wI444qVQ/Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t348q6m2g5e0g83ud86399cre7qtt2ykm2gt5vrmy68remzu9slqfd2js5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxblJxdHZqSHVIaWN0ZzEy
        OFd0ZXBPWmlqbnpkaThOeTZRNC9YdGs0ZWswCk9HQjVYdzNqZjRWRjNLL0Jua3M1
        ektNNFU2Qmw1blR2b0NzVTF5ZkJlT0kKLS0tIERmYUgvc3RMc2dzTU5QUkJsV0R3
        YWFvUGpiZ2VRRXVLaEt1dXpaN3F4WDQK7E/mWSqPR2pFPDEufbEUQa8h4CIHRJ1T
        aVIQjPn/dt4C4hEm9gb6bkA0lTVy46My7TTpZ+j/T3GvmukMyHjV7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T21:14:45Z"
  mac: ENC[AES256_GCM,data:sci4tjqV6RL+sdZojz+wuuiCZ9cXE6l2rlTVVVSw1Zos5UItSIgjqCCiY8ElrPh+HFrJEwvEAGewLBmmCfuMu1Y8/rE4H0dUK8DRAo269DuhqouadDwOpKuUHLwXf88OOvwodYLAJDjv7AGMSc2UU6iqNJCHYizd/yAbJddUokA=,iv:Qzf2SMuRPd84tOjeqvZ+Deb+i3JvTQt3+eeDpsjdYHY=,tag:U0ruaNtfCiEOZuc31ZaHrQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
