apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3ENEEtuJb2y+ijt4XojmL71QezMogT8ObAqS5Vp9i1L/tAt+Us+ubw==,iv:3XxONVTQE9v39xq+HaRePLzkOAuT6iZAa0HBAYhysiE=,tag:cawqfNpsBomB+TWTlz07VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV3lldWpaQjZubDMxbnNz
            SCtpQTZUNTRUVHZOL0tBQkJ2Slc2RWgxU2w4ClkySHFic29QZ3lEUWI5eE9ScGVY
            S21nMWNJbmtxTll5MnV0TFJNemxldzgKLS0tIFl6bVR0YS9CVzZYRjFCZjN4bUJY
            NndtRmx1dEdrT3VWRlozUXZNZGhZNDQKc7yL5qQurOhesJtIoJuQvPGZ7PH+Uh9/
            2TGEBRMyRhJJiM7Znh3TLNG+rmC3+TAAwsUVO7CqhpI8uTkDdPY6jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T11:37:50Z"
    mac: ENC[AES256_GCM,data:of/qkORyk3h0WOd0eP967ZN26fgWD3n40x659109k3+yRq2oLbjgaXnR02TMFmebJJJFkWheti9TJezWX8aBHVk5yEOege4CaSfLracf6wAwMLwKC+yXNxXkhHmnooCNwLKenIL8Iwm2MoYA7qKaTgokUCINaWwIkiQNMRt/ilA=,iv:4NmTB1TfnjnwoVZ/mmYYxQ4l5wEajLIe35N59tyb8pk=,tag:xJYURwIRHVBxEWvrBnJ6vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
