apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:xXtk7YUk5GTeRF6jCoK9XNGveB9vOSpTVlWeOm3Oq0MzmGzBPBVQpw==,iv:0foeCJCZBNpQXrQ6iGGl2RGNIFAj3QXj7x+YdgzKSJw=,tag:V9TncVzKhKDDEKdmTZRxDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WTNoY2paM3p2blhlTllI
            NENwRGdCdkdsVFNLT2JWdWZyTU9mbU9JekRvCjdzU25kcVhSZ0RuWm5MSkx4TWs1
            c2JkSWsrNmlKd1RHNkZZUXpEc0NpTmsKLS0tIGZ5YTBjM01NOEU4alhFdXpuNE1s
            TXZWWEwvaDBFcUxlZ3NxYjhjdVlWRGsKaZ/qEc/MPQOYfSj/pCiX1ulp6axUrdTv
            Zv5+MlUXtlMlzDnRKL40PtNN6QgvgYg8xI8KDHNakD3Ig1u16xIk1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:58:34Z"
    mac: ENC[AES256_GCM,data:ZzZ3r10IPkCyfg00HwTFx9OVNUgXY8/X8rWJWLC+ufGLV0bgrkC2cKnLYR+pZ4OU7L9qxFkz6tp4fReMvTi7KhMrouzFkReND2ojOMiSdT41Bj9X9HQQ5onGqTdbtweraelWyEMOZnxSZngnuI27dyuYNsMIa9hIq/SLcpcj6xo=,iv:P2jmjFO7aVgGFnK3ELoUXD/JV/NqIxw9VVfvGctKEQ4=,tag:bRjU9ySUpHAdt9NRPUUk8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
