---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openwebui
components:
  - ../../components/common
resources: []
  # - ./openwebui/ks.yaml