# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0TciXkDZbqxIchnro0FJ6z61PYdxRSN2kDXw/kb0fuCZCIs5v9IwHQFO4vEH52gZ/qtKoidOYfznFYeMAsPtmoPCezILR/82oJH7th1vJRdiEWXDVvh7RA3uOUYguAaZW6+WqGxDlGXZl4mqLD1CaTrviYh+OoH+IpigcqGZck23a1umY+EOcCB/FMK4URJIfOij5vIQneJIZ/bRF/UCxeFIeoEQw9UbzSw0CsU1vibWTj8I,iv:2FV8f/8Y75+8bwT6VH/tTw3n/zbz92rmbJ1XmY40M74=,tag:8mcAEYF0EcF2ng3iiNuACg==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M0svL05GQkdHMFM0NUxW
        MTVyd29qQVk0Y3dHcllyeG1URVRXVXpMd3pZCmJtT3dBNUwwZElJWE9wdkRnYzAw
        TW5UMENGSUhISm94em9oUFkzS1hDa2MKLS0tIGhRZTVQdng1MnJ2cTNRaURqcW93
        MkFEanpoMzJURHh3REN3T1JBSjZjK0EKILS5B9jSEvvGimaHFubWoGmsR1FlWfBF
        ihBEhvkoczoRhQG1ZTt2Gb2XrhfRwt/Npbn+uQDS913zMrexmUnkEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-14T17:25:21Z"
  mac: ENC[AES256_GCM,data:ObWyQuUMDIlisuZa4f/53BrmcSciWELGkT7Sk3nSjV1GpLl/BjG9S3c031df/1O+SUWse/4dLg00xU6Wh/sbfRJxNjESpD3EVd1Ujc0ci9jdAbUfD/dB+0TReAukUItuT1xwea7sBbkbl1xgpfZZTzLha3sI7YcbyZ8ba5S5qtg=,iv:iB32lDf/pr6VkKP/PGykADzohuqz6cCixHy+BInNeuU=,tag:5yf3n4fFJeLo+HKuD9gMhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
