---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-runner
components:
  - ../../components/common
resources:
  - ./forgejo-runner/ks.yaml
patches:
  # Docker-in-Docker needs a privileged sidecar. This namespace is the only app namespace that allows it.
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: privileged
