---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    extraEnv:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pihole-password-secret
            key: pihole-password
    extraArgs:
      - --source=service
      - --source=gateway-httproute
      # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
      # You don't need to set this flag, but if you leave it unset, you will receive warning
      # logs when ExternalDNS attempts to create TXT records.
      - --registry=noop
      # IMPORTANT: If you have records that you manage manually in Pi-hole, set
      # the policy to upsert-only so they do not get deleted.
      - --policy=upsert-only
      - --provider=pihole
      # Change this to the actual address of your Pi-hole web server
      - --pihole-server=http://10.127.0.3
    triggerLoopOnEvent: true
    policy: sync
    sources: ["gateway-httproute", "service"]
    # txtOwnerId: main
    # txtPrefix: k8s.main.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
