# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pihole-password-secret
stringData:
  pihole-password: ENC[AES256_GCM,data:FhqAvIyi61Cq2I3xkSP8DkwC0/9sdx/S5Y6E/5Tq+4s=,iv:HLLwii4F40qYTbh13ANLKeKeU8wex1gLVzQzUU4a9I4=,tag:NrADmtR6orB8nLzovtpBKg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2trU1pnTGZIRGRxMm9M
        SUx1a3VZbFkwN3BZNzRQQS9LK1UwcGpRYVU4ClJrN0pMQXZEcjNpWVJsRDVkZ0tM
        d1JpWXRsTzc1VXdyY014L2NBczBqY3cKLS0tIHhIcDE3UE8rL1ErblZGNDZnTnBj
        SjZlajArSC9nMWc5UjE2ZlJNRGlpSVUKT9Q3dAe/n9bO22WIkgZr0+xy7YaCM9m9
        AdeeKt3Bsm4fgBif+h8+NMb8HUuXThJPbZPIH7h7Msj40L2DMi95UQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T15:53:00Z"
  mac: ENC[AES256_GCM,data:Y+nKPTpvMFQuwiau0M1U71m2yvT1Bhf9eWC+mcAmgttKbSw6d3L+IEC7373NnXuj/fcsBYH5/A9SnGlhTIBIutPc0Q5RKaEn3nJLwhB6BPDfy6RV9GxZRgz+q3L1Ac43pe2mUm7R7benruOACwtohTWhwSEZwv9KVYp5Shp5wN8=,iv:3nc5TbfMvz+Mzi83030TSSkl/MLKo0vyYpvmsab9cZM=,tag:9LfqIKEY34zbwr8rTcLSeQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
