---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: romm-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: romm-auth-secret-key
