---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: romm-library-pv
  resources:
    requests:
      storage: 8Ti
