# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.127.0.40:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.127.0.40"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "kube1"
    ipAddress: "10.127.0.41"
    installDiskSelector:
      serial: "24374AFF58D1"
    # installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/65cf8364cd0de4cf7b851dc7067a2db83d0ba04f11d8635c6cd3334be6ffb825
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:30:c5:ed"
        dhcp: false
        addresses:
          - "10.127.0.41/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.127.0.1"
        mtu: 9000
        vip:
          ip: "10.127.0.40"
  - hostname: "kube2"
    ipAddress: "10.127.0.42"
    installDiskSelector:
      serial: "2417485DE2C9"
    # installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/65cf8364cd0de4cf7b851dc7067a2db83d0ba04f11d8635c6cd3334be6ffb825
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:30:c3:be"
        dhcp: false
        addresses:
          - "10.127.0.42/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.127.0.1"
        mtu: 9000
        vip:
          ip: "10.127.0.40"
  - hostname: "kube3"
    ipAddress: "10.127.0.43"
    installDiskSelector:
      serial: "2410480AE482"
    # installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/65cf8364cd0de4cf7b851dc7067a2db83d0ba04f11d8635c6cd3334be6ffb825
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:30:c5:26"
        dhcp: false
        addresses:
          - "10.127.0.43/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.127.0.1"
        mtu: 9000
        vip:
          ip: "10.127.0.40"

  # - hostname: "kube4"
  #   ipAddress: "10.127.0.44"
  #   installDiskSelector:
  #     serial: ""
  #   # installDisk: "/dev/nvme0n1"
  #   machineSpec:
  #     secureboot: false
  #   talosImageURL: factory.talos.dev/installer/65cf8364cd0de4cf7b851dc7067a2db83d0ba04f11d8635c6cd3334be6ffb825
  #   controlPlane: true
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "38:05:25:30:c5:26"
  #       dhcp: false
  #       addresses:
  #         - "10.127.0.44/24"
  #       routes:
  #         - network: "0.0.0.0/0"
  #           gateway: "10.127.0.1"
  #       mtu: 9000
  #       vip:
  #         ip: "10.127.0.40"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

