apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MB1W4UwIomXF6XRV,iv:USi2qSc1FQdoGTsR0D3moMnt7tRF1QHSAYhve11GzDI=,tag:Aol7t0xszHMNlQCjJSBEbA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GKLHo/HxXG71afzx7aSGf1qY,iv:ey7Kz8CJUfY2NbOD+0FiZs30xJ+tNg66QQyndfvHKKA=,tag:J7Uyhf3zUDmBFF+O8wx8eA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OiSo5zbmBnt/qPMw920ayHoLy8lcb7bAiBU/1lOg1nn7TLQr,iv:xTtCrTupvMYgZsFWzgYZIr8m9TklzLsix8kZmmZ7vs8=,tag:L9BcZwUTo+CFBX4e3kQV1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNnBoSFVEMWVDMXRuT3Fi
            VVQzU0I1cHJ1U05JMGVQVkJoRWd1Vzg0am53CmI1dXB4aGdpU01EaERUazg2TmJ5
            UkZzYnByZzRQdGE2NGV4aS9OSU4yQ0kKLS0tIFZVdWNaMXBxN0FFWWN2d2U2Z3A4
            bW5WRWZrTllWYVc2OFF0b2FENHBzZjgKrgeOMeJoytCwu0nJYSM1yFpuIbl07Jnw
            +WHZxNJZKdKTUa5oJjkLWKm76cLKD4LmsfAgQd8CwZCQLbO2t5xoOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:58:34Z"
    mac: ENC[AES256_GCM,data:NsuVe1bNQ/syCVh/vCsLJ2VzkxpiptaABy7gUeHny+kifO6yZ6YAgbq7P9kjlyLOUqXXqS4vVZJFmMLBZN8omL1S0M+e4XErzqjlG9eQgKsKmKpX8vGWGmYgxRx3NvT85aT6O1tio62meh5AfvLjPvceN6eYycEetcpKsKf+iXc=,iv:+32imyjL9/f0xMB4O0/PgRqncADqrLCPiEOomWZolOA=,tag:yre6gmzkvgii+sariu2gLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
