apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iF/Fgyc/4AUSI98a,iv:edzhxveoHyiDSS0g3xc1T7KBKtUypPsXIbiboOBjMmg=,tag:OAU9SeMaRHc94hNiaFPnaA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HdkqHrHVSF8Pe45/PXhipbxS,iv:2R5qhYErSs1vOIFzQCNdnfM5l79Xs3l2sCEz0Lr2Ccg=,tag:p46sxSAPacJ4oHUsX74wAg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0w3szdgS0L7LxxDZFrFQ8NWIvfO22rXK7VzzY7RryJD/TEYY,iv:Puz2ph0VMgvRAFvUJNVGWOloTneE5TsV2JrrFMYGDlg=,tag:59uy9ZtaYrJl8qHrxXoa2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUXdoeFdRVEM1MFBJdE9q
            MUo3QmJKaCtCSi9XQnNzV29zcGdKSEVXSENZCnRERzQ3NzFjY3BMNEl4MGw5cDRT
            aEhhelVUNXBGZkt5UTYreDJjMmJrYlUKLS0tIExKTjRhYUxQRnFWWXNCU2E4ZExK
            c0hwd2NrMGo0c2dpUGtEM09oUDVENkkK4/P4NEKd29mzdB1eQzLLa8UOlnXqux/C
            Ii2zQehytQw6LFQgviqqBF9Lb9qVI8MKHjss2zbD3jBToYoz6cjrSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T11:37:50Z"
    mac: ENC[AES256_GCM,data:ROzcpP+ScfEqF14N5+1mFdv1RPlqirjraLIHp5cy32lvbvc+jtYs9VFK7jG8yxkAuFTwzat3KDQKx4qWL44xdkgWsLp0k2iJumXRYFUdUuvqgDU8DWI9uXQHocqTHBsKfUj1yIE3NBw2FHifmSZn6bcwZmz1+ikbv3BFrJi8GUc=,iv:0UWdG/Xpf4kTNJT8Sp3BdSIPAy4PE29vUiIMcGjNZt0=,tag:WziD0NxeelKndaqEeiBYVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
