---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: firecrawl-helm
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/winkkgmbh/firecrawl
  ref:
    tag: 0.2.0
