# https://artifacthub.io/packages/helm/open-webui/open-webui?modal=values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocm-k8s-plugin
spec:
  interval: 1h
  chart:
    spec:
      chart: amd-gpu
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: rocm-k8s-plugin
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    nfd:
      enabled: true

    labeller:
      enabled: true

    dp:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.31.0.8"
      resources: {}
      # Set daemonsets updateStrategy for device plugin
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1

    lbl:
      image:
        repository: docker.io/rocm/k8s-device-plugin
        tag: "labeller-1.31.0.8"
      serviceAccount:
        annotations: {}
      securityContext:
        privileged: true # Needed for /dev
        capabilities:
          drop:
            - ALL
          add:
            - CAP_SYS_ADMIN
        readOnlyRootFilesystem: false # true if -logtostderr flag set in labeller
      # If you do want to specify resources, uncomment the following lines, 
      # adjust them as necessary, and remove the curly braces after 'resources:'.
      resources: {}
        # limits:
        #   memory: 20Mi
        #   cpu: 100m
        # requests:
        #   memory: 30Mi
        #   cpu: 150m
      # Set daemonsets updateStrategy for labeller
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1

    imagePullSecrets: []

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL

    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

    node_selector_enabled: false
    node_selector:
      feature.node.kubernetes.io/pci-0300_1002.present: "true"
      kubernetes.io/arch: amd64
