---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pelican-secrets
  labels:
    app.kubernetes.io/name: pelican
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: pelican-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: pelican-app-key
