---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui
spec:
  parentRefs:
  - name: external
    namespace: kube-system
    sectionName: https
  hostnames: ["pelican.endsys.cloud"]
  rules:
    - backendRefs:
        - name: open-webui # needs to be with the dash
          port: 80