---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./pvc.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
