apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:SKZxBmh5tEC4wF0ypbbJ4TWg7GxJgjfbsWwKI7qPoRY=,iv:Mx2wva3DEDviUD+w2A+OSts2EAel3WxbriSDkU+R4gE=,tag:f6mrVwEwI/JiD+BZo0uPUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycS9PM2RRalA2K2xZbEh4
            UHdzR3diZEF1VGVrZkhxV1lqSkV2eVV0OFdjClFOQVZhN0cvUGw1S1lyTi93M3oy
            UytCRmlrWDZWbFlqRzBaR3QweE5LZXMKLS0tIExiL3czOVVRZG9DaW9wayt3VkNZ
            NzVWbWZTMmhVU3UxSWl4L2greDB0Mk0KWbxS3gdus7W8eYnXkrIa98ei+n7FYixg
            1i5V4whwazv919+ThYVaG5SYrIhy2w/wMJFGz8JKVTm2ZbfvecDfsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T11:37:50Z"
    mac: ENC[AES256_GCM,data:yj8KW9WHUVP+qZwzDMorbjJQVX5+DXnUFT81jU2LBPqdobsHmsrPH3bWu9+CF+XHG4EZH/wEum5jdJUJwEqJL6WiRzRQdRTJnB0f8YXyyC8Aidplti3/RtMUcCJZU5P6bFJgduJLZiGl3nIdIXObsBm4HiAmLt7FU1bJk2LProg=,iv:fxBOV/yqduwWxu8shhC1kDIEc6PAxwhdrQH85R191h8=,tag:7IXkmPRU0HvPvJVy0TcBHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
