apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7ACsCTxm9OQJBZF3y4vFPjZfV+qwW9vuXixoS1YhDBw=,iv:xrb/hY6wXxdSdEMVGo+L5ncFlIczTAhZgEQ2YaI/J+c=,tag:FE2v1vim4r38Mvun8S+MeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVklvMHkyblFsdXJLc2Zz
            Z3RjaFUxR3hnNzdBcklUTXRqT3dkVG5NZkN3CnVjQU5UalE2c3V3RzFyY3k3Zjg2
            aXROZGUzbEtJbjdIMVJXNTRNUEZvYTQKLS0tIGpUbUs1Z2RrNjhVT3YxTWU0MThQ
            ZnhXZW92djFmZm1WcTBBVDlOb1VFZEkKOawZJ4btd7bPah7zQpNvjxgzhVJXsb9I
            xh/l9ieXLO4iX0qwTFFfxjZD4y2vwNMR650F2/zyuFfXzeA96uJ0rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:58:34Z"
    mac: ENC[AES256_GCM,data:vZNXHUq5VC3w8/QdQHrATKYFbSJ0OrcWOSHLq7l48V0QYD/cMzKwcZI1FHi0rEDw8SpSeo3RB0Pg6NH7ixWuLV/3FXDlizBgc7ijzH4JKMpRbFgbSNkev+c/DuOgz5k+eG5LvZEX58GY2Loip6Cev9HjIOOR4y/Ay6/w/yxtGAQ=,iv:riXW1u7NMXAcv7uRxQbWzGfAf60HKgaCmaG9QxA9qgA=,tag:h8RU5NCvjgB75d1PlQh0GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
