---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitwarden
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitwarden.com/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sm-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: bitwarden/sm-operator
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    containers:
      manager:
        image:
          # NOTE:  This should be updated before the final PR
          repository: ghcr.io/bitwarden/sm-operator
          # Will default to the Chart's AppVersion, but you can override here.
          tag:
        # The pod resource requirements.  You can adjust these up and down for your environment
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      kubeRbacProxy:
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
        # The pod resource requirements.  You can adjust these up and down for your environment
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
