---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    service:
      ui:
        # -- Service type for Longhorn UI. (Options: "ClusterIP", "NodePort", "LoadBalancer", "Rancher-Proxy")
        type: ClusterIP
        # -- NodePort port number for Longhorn UI. When unspecified, Longhorn selects a free port between 30000 and 32767.
        nodePort: 80
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultClassReplicaCount: 3
      relaimPolicy: Delete
      volumeBindingMode: "Immediate"
      defaultDiskSelector:
        enable: true
        selector: "nvme"
    metrics:
      serviceMonitor:
        enabled: true