# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ju1qe1tRV/FcibKT8r84BkODu6oaBsS0hyOqnAjOMhxRHQdoMtrCug==,iv:rW9vINd3U0nYFyV30v3z3lXhNyV5j0uqwjHqGmvpo1k=,tag:vM6KrU863N/V1RzA+PZ4Bw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1t348q6m2g5e0g83ud86399cre7qtt2ykm2gt5vrmy68remzu9slqfd2js5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVG1FOHRicVpmWVZKVm14
        b2lWaW1kNzJaTDhUempidnlDU21QTENvNGtFClB2VmZqaWFEd01qclNGSzBTUGxB
        bWFsRlUxZUdjUGttZXR4M0lRZ3NWcHMKLS0tIDVjWXFMb3ZUb1JkU292dk8rYWQ1
        Znlwd3lXMHA5cm5lVzBtbXFrSHBMWVkKYOqs0GYu3wxUtX9ioGnEJ0rQbZ/VB8rp
        g0BI0eF7et/gLdYuyQhdpDG7FhQlz0PtBBOiYIZKTmeR9U5amajnMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T21:14:45Z"
  mac: ENC[AES256_GCM,data:z72ATiFH+gD7hcN37AKGIet1Pla6KL3NtmcHy2KGn4DXu8Obcy9aqJSXvSkZ0fJg+bAeB7TOULDWnZVPhOXl+n3xMV0RBB4Lg9+VEDz4yjxCEMajf7d0amOjnjjM7iPiTuEy9st4FwbrRzCiE0qS6uBxWWKT02RB+UEI5PPS4zg=,iv:1/3zkBaQtV4D4wdjCRZ+Z3ufR4yS8nL6dP10Vu2BdQ4=,tag:hAUliNHO07M3up6Jl12kKQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
