apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:g/lNYnY1hJiSgKE0PAWkI6CSTZ9UIfDRQfhvlUUk80htCeMo741JSw==,iv:7bvp/nsI4k+V1U0k461RoGbfvvv4pLtAAkjZl9Y4I2Q=,tag:VP1n0K6tztupicz6+wX/nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMEVraVJHKzVvdGozZi9o
            RXBHUlA0ZUZMVFRNd2YyUjRWZm1EckxXUEhFCmdqMlNTaEJvZEdIVi9Eck10T2cy
            K0pUUCs0LzJSZ2JBanhlam9NdWpGNTgKLS0tIDUxRXFJQzd5UFcxdWtyQVprbE1a
            azdSS2VOcFRNTHo4M1dmSHhBTFhNL0UKaTocpYOkEWngBlTJH7+TYjFyYacSp2SQ
            /YbcW0+RCtedFM+WasbP1zuIcNUfk3nH95enKIcQfrmFhr1V+IobCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T11:37:50Z"
    mac: ENC[AES256_GCM,data:w/g3YgJ4HZumwQXLzzVXSwzsU+bO3KmmuRwhPKsizhGBK0/fb0+YU0OIAQ4jCFprBfEkxXXt7/bEn7ahxu2vEmBJAmTRgtniH1wN2CsiZdlk6gjOGEC0nk1tVsV6UuZDjIwNECTaVGpTOwx2RKhMR764P04DB7RE0CBzOGzu2dM=,iv:u5R5ZDnLK+Iv4WtLX1I7CytprmN0wkObRBa1i2zTnK0=,tag:0+U4Hpcz+7SdiGXkLsWaCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
