apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:lEoTo40H3u5LWAeHXMwIu2+8nuM6ofv01cAROgPxWdmFL5Dd/H5z9A==,iv:b3C1afGxjrvRjWjCTkMKy+8plRMM1qm1D4xj5cMTFBo=,tag:BDDzKFzpO3g7KRPTti8fAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aen2av983p0apwu3nh3qazagtd3ljwmhkaxw0638877c2kt7z4lse06543
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa3R5YnlseWdTL21mTXpX
            SHdpRnVHb1BLdUx3T3R2VEtrUWRjMTdEOEUwCjFTMG56aXJHQThsa1haLytIT3hY
            NzJEMXY4L2lIS0kvT2ZVNWpnMnVnZW8KLS0tIFNWV1E0ZFNtelRzTWZCbFM5OG04
            K05DR1B6aFJTcGRaZXRFSWRUOFZQY1EKZEhcU0wMQ4+OJ2Mly3g0ZV9gKtrv/ygM
            WZWqKbB5CymzjdFsClO/bUSkZCrH8e2UWijsnXkB5wgt6MUYi2WymA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:58:34Z"
    mac: ENC[AES256_GCM,data:ro1c3UBC6Z5UVYYzQcgbh/oJxqv6HujWppxeLbWrz1ifr6RgBL186/RJ82cT7uC0+8ENHx0sh9WYoS0Tmb/r13rjbuFcMNzkhqUyu4VxcxwEiS5o4GQv5k22pthLSS2UY8pZyTN7H66Zrbwr7aRNIv+0HcGPgKS4IYFDKimzDRM=,iv:fY3UfA6+oeWoUvY9R+nkJydxXrGuIzamFj6AY2siUrI=,tag:YfMK8dXuhKujb5PfGyptuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
