apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:BOmSan90PkoPQ3EOySj1T09qeRZIE1Fbc43Hw3AiwfN2EMXVlE6bS+DtPVs0hyoqKyaIqQsPsktgZSx1ldq7/ocDRKQE1XSMyy4GA5NSGy0uQFxt+PBq18W3Is79W39gnqxadtUZ6uDPnMTChJeVGW4fb6gd/7yGvg3cD0hN0V0ZNChPYXs2r66r2DFW2IKG8jAAijlj1iwVBe1SMBTWEaYiXH4=,iv:n1pXzh88rV6sJuHkNE0hE0I5CElZX6nlN6mzeN/qxBQ=,tag:H9SD10sk8S0N7lcB1/PD3Q==,type:str]
sops:
  age:
    - recipient: age1g7lkx9fgvslwxmz09tkn9896zkux5vxvhplt6xsjxg33x2z4rvyquw83y8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcS9mYUdJeTlGV0E1TStK
        dzNjSHZhZks3TEZzbzBUc1NIODNZTzJXWEZRCkc3VkdCdzRaZXpXT1AzcDd6RGhC
        L0pPc291dFlZVWhGWWZSaXovY09ZWFUKLS0tIGNURkMvWFgwM1FPTVpBRWZCeEVD
        cDRrWkE1YWVBNndUbnJucCszRzRoYmcKtP+CCaBUMZ7F2m8Pu+HzEk0q1ThAK5jB
        H8G4rMR2TuVWVfU5AuzP6I24qAuoWvZVnnZGU/rdkdBJf8QhK9FguA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-20T00:05:04Z"
  mac: ENC[AES256_GCM,data:yjWyw/KuBV55ABfYWnVfUm+YJc2mKyIM0ddHKgxGGa1aYaqlW6bWyQZ9vNCEa0QF2VqRBrG6XqusBFEj2doFCDQLHcdnvNU8vr2tQEjYJV+3jbG4wFNVMFFeEM/r9+IRsAUSq7plxgMI8QAkEec4L0qlqilhDR122OYdDQmOX6M=,iv:guEjztW8Hcki0zZmJmkWpaYQMIE234wUxM1XG2aVoSs=,tag:0kmJEuMo6cSrOX3xTil+Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
