---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hindsight-postgres
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  bootstrap:
    initdb:
      database: hindsight
      owner: hindsight
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
  storage:
    storageClass: longhorn
    size: 10Gi
