# https://artifacthub.io/packages/helm/open-webui/open-webui?modal=values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cleon
spec:
  interval: 1h
  chart:
    spec:
      chart: ollama
      version: 1.32.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Ollama parameters
    ollama:
      port: 11434
      gpu:
        enabled: true
        type: 'amd'
      models:
        pull:
          - gpt-oss:latest
        run:
          - gpt-oss:latest
        clean: true
    persistentVolume:
      enabled: true
      size: 30Gi
    nodeSelector:
      kubernetes.io/hostname: "kube3"
