# https://artifacthub.io/packages/helm/open-webui/open-webui?modal=values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cleon
spec:
  interval: 1h
  chart:
    spec:
      chart: ollama
      version: 1.32.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # image:
    #   repository: ollama/ollama
    #   pullPolicy: IfNotPresent
    #   tag: "0.12.3-rocm"
    ollama:
      port: 11434
      gpu:
        enabled: true
        type: 'amd'
        number: 1
      models:
        pull:
          - gpt-oss:latest
        run:
          - gpt-oss:latest
        clean: true
    persistentVolume:
      enabled: true
      # size: 30Gi
      existingClaim: "cleon-data"
    resources:
      limits:
        amd.com/gpu: 1
        memory: 16Gi
        cpu: "8"
      requests:
        amd.com/gpu: 1
        memory: 16Gi
        cpu: "4"
    nodeSelector:
      kubernetes.io/hostname: "kube3"
    extraEnv:
        - name: HSA_OVERRIDE_GFX_VERSION
          value: "10.3.0"
        - name: OLLAMA_KEEP_ALIVE
          value: "24h"
        - name: OLLAMA_NUM_PARALLEL
          value: "4"

